project:
  type: website
  output-dir: docs

website:
  title: "Darren Lin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - checksplit.qmd
      - example_analysis.qmd

  page-footer:
    background: light
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/darrenselin/
      - icon: github
        href: https://github.com/darrenlingit

format:
  html:
    theme: yeti
    background-color: #1f9ef0;
    css: styles.css
    toc: FALSE
    page-layout: full



