project:
  type: website
  output-dir: docs

website:
  title: "Darren Lin"
  navbar:
    background: "#f9f9f9"
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: CV.qmd
        text: CV


  page-footer:
    background: light
    right:
      - icon: envelope
        href: mailto:darresl1@ucla.edu
      - icon: linkedin
        href: https://www.linkedin.com/in/darrenselin/
      - icon: github
        href: https://github.com/darrenlingit

format:
  html:
    theme: default
    background-color: "#dad9d9"
    css: styles.css
    toc: FALSE
    page-layout: full



